//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 192.145639 on Stable branch
// Generated with ALiVE version 1.11.3.1905291
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_USMilitia {
        displayName = "US Local Militia";
        side = 2;
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 15;
    };
};

class CfgGroups {
    class Indep {

        class I_USMilitia {
            name = "US Local Militia";

            class Infantry {
                name = "Infantry";

                class i_usmilitia_infantry_militia_group {
                    name = "Militia Group";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.7;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M16A2_01";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                    class Unit4 {
                        position[] = {9,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Modified_AR_01";
                    };
                    class Unit5 {
                        position[] = {11,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit6 {
                        position[] = {13,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Automatic_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {15,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Sniper_01";
                    };
                    class Unit8 {
                        position[] = {17,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Hunting_Rifle_01";
                    };
                    class Unit9 {
                        position[] = {19,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "I_USMilitia_Militiaman_FN_FAL_01";
                    };
                };

                class i_usmilitia_infantry_militia_patrol {
                    name = "Militia Patrol";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M16A2_01";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Automatic_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Modified_AR_01";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Hunting_Rifle_01";
                    };
                    class Unit4 {
                        position[] = {9,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "I_USMilitia_Militiaman_FN_FAL_01";
                    };
                };

                class i_usmilitia_infantry_militia_team_aa {
                    name = "Militia Team (AA)";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_AA_Specialist_01";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_AA_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_AA_Specialist_01";
                    };
                };

                class i_usmilitia_infantry_militia_team_at {
                    name = "Militia Team (AT)";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Modified_AR_01";
                    };
                };

                class i_usmilitia_infantry_militia_demolitions_team {
                    name = "Militia Demolitions Team";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Mechanic_01";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Mechanic_01";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militia_Bomb_Builder_01";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militia_Bomb_Builder_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class i_usmilitia_motorized_technicals {
                    name = "Technicals";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {3,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {-5,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CUP_O_LR_SPG9_TKM";
                    };
                    class Unit2 {
                        position[] = {-5,-7,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CUP_O_LR_MG_TKM";
                    };
                    class Unit3 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                };

                class i_usmilitia_motorized_motorized_group {
                    name = "Motorized Group";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.1;

                    class Unit0 {
                        position[] = {3,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {-5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CUP_O_Ural_ZU23_TKM";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M16A2_01";
                    };
                    class Unit4 {
                        position[] = {9,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                    class Unit5 {
                        position[] = {11,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Militiaman_FN_FAL_01";
                    };
                    class Unit6 {
                        position[] = {13,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit7 {
                        position[] = {15,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit8 {
                        position[] = {17,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Automatic_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {19,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Sniper_01";
                    };
                    class Unit10 {
                        position[] = {21,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Modified_AR_01";
                    };
                };

                class i_usmilitia_motorized_motorized_patrol_humvee {
                    name = "Motorized Patrol (Humvee)";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {3,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit2 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit3 {
                        position[] = {9,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                    class Unit4 {
                        position[] = {11,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Militiaman_FN_FAL_01";
                    };
                    class Unit5 {
                        position[] = {13,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Hunting_Rifle_01";
                    };
                    class Unit6 {
                        position[] = {-13,0,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_USMilitia_Humvee_M2_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class CUP_O_TK_INS_Soldier;
    class CUP_O_TK_INS_Soldier_OCimport_01 : CUP_O_TK_INS_Soldier { scope = 0; class EventHandlers; };
    class CUP_O_TK_INS_Soldier_OCimport_02 : CUP_O_TK_INS_Soldier_OCimport_01 { class EventHandlers; };

    class CUP_O_TK_INS_Bomber;
    class CUP_O_TK_INS_Bomber_OCimport_01 : CUP_O_TK_INS_Bomber { scope = 0; class EventHandlers; };
    class CUP_O_TK_INS_Bomber_OCimport_02 : CUP_O_TK_INS_Bomber_OCimport_01 { class EventHandlers; };

    class I_USMilitia_Militiaman_AR_01;
    class I_USMilitia_Militiaman_AR_01_OCimport_01 : I_USMilitia_Militiaman_AR_01 { scope = 0; class EventHandlers; };
    class I_USMilitia_Militiaman_AR_01_OCimport_02 : I_USMilitia_Militiaman_AR_01_OCimport_01 { class EventHandlers; };

    class CUP_O_TK_INS_Soldier_AA;
    class CUP_O_TK_INS_Soldier_AA_OCimport_01 : CUP_O_TK_INS_Soldier_AA { scope = 0; class EventHandlers; };
    class CUP_O_TK_INS_Soldier_AA_OCimport_02 : CUP_O_TK_INS_Soldier_AA_OCimport_01 { class EventHandlers; };

    class CUP_O_TK_INS_Guerilla_Medic;
    class CUP_O_TK_INS_Guerilla_Medic_OCimport_01 : CUP_O_TK_INS_Guerilla_Medic { scope = 0; class EventHandlers; };
    class CUP_O_TK_INS_Guerilla_Medic_OCimport_02 : CUP_O_TK_INS_Guerilla_Medic_OCimport_01 { class EventHandlers; };

    class CUP_O_TK_INS_Soldier_AT;
    class CUP_O_TK_INS_Soldier_AT_OCimport_01 : CUP_O_TK_INS_Soldier_AT { scope = 0; class EventHandlers; };
    class CUP_O_TK_INS_Soldier_AT_OCimport_02 : CUP_O_TK_INS_Soldier_AT_OCimport_01 { class EventHandlers; };

    class CUP_O_TK_INS_Soldier_TL;
    class CUP_O_TK_INS_Soldier_TL_OCimport_01 : CUP_O_TK_INS_Soldier_TL { scope = 0; class EventHandlers; };
    class CUP_O_TK_INS_Soldier_TL_OCimport_02 : CUP_O_TK_INS_Soldier_TL_OCimport_01 { class EventHandlers; };

    class CUP_O_TK_INS_Sniper;
    class CUP_O_TK_INS_Sniper_OCimport_01 : CUP_O_TK_INS_Sniper { scope = 0; class EventHandlers; };
    class CUP_O_TK_INS_Sniper_OCimport_02 : CUP_O_TK_INS_Sniper_OCimport_01 { class EventHandlers; };

    class CUP_O_TK_INS_Soldier_AR;
    class CUP_O_TK_INS_Soldier_AR_OCimport_01 : CUP_O_TK_INS_Soldier_AR { scope = 0; class EventHandlers; };
    class CUP_O_TK_INS_Soldier_AR_OCimport_02 : CUP_O_TK_INS_Soldier_AR_OCimport_01 { class EventHandlers; };

    class CUP_B_M1151_M2_WDL_USA;
    class CUP_B_M1151_M2_WDL_USA_OCimport_01 : CUP_B_M1151_M2_WDL_USA { scope = 0; class EventHandlers; class Turrets; };
    class CUP_B_M1151_M2_WDL_USA_OCimport_02 : CUP_B_M1151_M2_WDL_USA_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class C_man_1;
    class C_man_1_OCimport_01 : C_man_1 { scope = 0; class EventHandlers; };
    class C_man_1_OCimport_02 : C_man_1_OCimport_01 { class EventHandlers; };


    class B_USMilitia_Militiaman_M16A2_01 : CUP_O_TK_INS_Soldier_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (M16A2)";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "CUP_U_I_GUE_Anorak_01";

        linkedItems[] = {"CUP_V_B_ALICE","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_ALICE","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M16A2"};
        respawnWeapons[] = {"CUP_arifle_M16A2"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_I_GUE_Anorak_01",{{"FirstAidKit",2},{"CUP_30Rnd_556x45_Stanag",1,30}}},{"CUP_V_B_ALICE",{{"SmokeShell",2,1},{"CUP_30Rnd_556x45_Stanag",6,30}}},{},"","G_Bandanna_aviator",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_USMilitia_Militia_Bomb_Builder_01 : CUP_O_TK_INS_Bomber_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Militia Bomb Builder";
        side = 0;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "CUP_U_B_US_BDU_roll_glove";

        linkedItems[] = {"CUP_V_B_ALICE","H_Booniehat_oli","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_ALICE","H_Booniehat_oli","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M4A1"};
        respawnWeapons[] = {"CUP_arifle_M4A1"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};

        backpack = "CUP_B_AlicePack_OD";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M4A1","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_B_US_BDU_roll_glove",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_Stanag",1,30}}},{"CUP_V_B_ALICE",{{"CUP_30Rnd_556x45_Stanag",6,30}}},{"CUP_B_AlicePack_OD",{{"ToolKit",1},{"MineDetector",1},{"CUP_IED_V2_M",2,1}}},"H_Booniehat_oli","G_Lowprofile",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_USMilitia_Militiaman_Modified_AR_01 : CUP_O_TK_INS_Soldier_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (Modified AR)";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "CUP_U_I_GUE_Anorak_03";

        linkedItems[] = {"CUP_V_B_GER_Carrier_Rig_2_Brown","CUP_H_US_patrol_cap_OD","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_GER_Carrier_Rig_2_Brown","CUP_H_US_patrol_cap_OD","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M4A1"};
        respawnWeapons[] = {"CUP_arifle_M4A1"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M4A1","","acc_flashlight","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_I_GUE_Anorak_03",{{"FirstAidKit",2},{"CUP_30Rnd_556x45_Stanag",1,30}}},{"CUP_V_B_GER_Carrier_Rig_2_Brown",{{"CUP_30Rnd_556x45_Stanag",6,30},{"SmokeShell",2,1}}},{},"CUP_H_US_patrol_cap_OD","CUP_G_Oakleys_Drk",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_USMilitia_Mechanic_01 : I_USMilitia_Militiaman_AR_01 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mechanic";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "CUP_U_B_US_BDU_roll2";

        linkedItems[] = {"CUP_V_O_SLA_M23_1_BRN","CUP_H_US_patrol_cap_OD","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_SLA_M23_1_BRN","CUP_H_US_patrol_cap_OD","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M16A2"};
        respawnWeapons[] = {"CUP_arifle_M16A2"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};

        backpack = "B_TacticalPack_blk";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_B_US_BDU_roll2",{{"FirstAidKit",2},{"CUP_30Rnd_556x45_Stanag",1,30}}},{"CUP_V_O_SLA_M23_1_BRN",{{"SmokeShell",2,1},{"CUP_30Rnd_556x45_Stanag",2,30}}},{"B_TacticalPack_blk",{{"ToolKit",1}}},"CUP_H_US_patrol_cap_OD","CUP_G_Oakleys_Drk",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_USMilitia_AA_Specialist_01 : CUP_O_TK_INS_Soldier_AA_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "AA Specialist";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "CUP_U_B_US_BDU_roll_glove";

        linkedItems[] = {"CUP_V_O_SLA_M23_1_OD","H_ShemagOpen_tan","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_SLA_M23_1_OD","H_ShemagOpen_tan","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M4A1","CUP_launch_FIM92Stinger"};
        respawnWeapons[] = {"CUP_arifle_M4A1","CUP_launch_FIM92Stinger"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_Stinger_M","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_Stinger_M","CUP_30Rnd_556x45_Stanag"};

        backpack = "B_Carryall_oli";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M4A1","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{"CUP_launch_FIM92Stinger","","","",{"CUP_Stinger_M",1},{},""},{},{"CUP_U_B_US_BDU_roll_glove",{{"FirstAidKit",1}}},{"CUP_V_O_SLA_M23_1_OD",{{"CUP_30Rnd_556x45_Stanag",5,30}}},{"B_Carryall_oli",{{"CUP_Stinger_M",1,1}}},"H_ShemagOpen_tan","G_Lowprofile",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_USMilitia_Bonesetter_01 : CUP_O_TK_INS_Guerilla_Medic_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Bonesetter";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "CUP_U_I_GUE_Flecktarn3";

        linkedItems[] = {"CUP_V_B_RRV_Medic","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_RRV_Medic","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M16A2","CUP_hgun_Glock17_blk"};
        respawnWeapons[] = {"CUP_arifle_M16A2","CUP_hgun_Glock17_blk"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_17Rnd_9x19_glock17","CUP_30Rnd_556x45_Stanag","CUP_17Rnd_9x19_glock17"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_17Rnd_9x19_glock17","CUP_30Rnd_556x45_Stanag","CUP_17Rnd_9x19_glock17"};

        backpack = "CUP_B_AlicePack_Khaki";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{"CUP_hgun_Glock17_blk","","","",{"CUP_17Rnd_9x19_glock17",17},{},""},{"CUP_U_I_GUE_Flecktarn3",{{"FirstAidKit",2},{"CUP_30Rnd_556x45_Stanag",1,30},{"CUP_17Rnd_9x19_glock17",1,17}}},{"CUP_V_B_RRV_Medic",{{"SmokeShell",3,1},{"CUP_30Rnd_556x45_Stanag",5,30},{"CUP_30Rnd_556x45_Emag",2,30},{"CUP_17Rnd_9x19_glock17",2,17},{"SmokeShellBlue",2,1}}},{"CUP_B_AlicePack_Khaki",{{"Medikit",1},{"FirstAidKit",5}}},"","G_Bandanna_oli",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_USMilitia_Militiaman_Hunting_Rifle_01 : I_USMilitia_Militiaman_AR_01 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (Hunting Rifle)";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "U_BG_Guerrilla_6_1";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_3","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_3","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_srifle_LeeEnfield_rail","CUP_hgun_Glock17_blk"};
        respawnWeapons[] = {"CUP_srifle_LeeEnfield_rail","CUP_hgun_Glock17_blk"};

        magazines[] = {"CUP_10x_303_M","CUP_17Rnd_9x19_glock17","CUP_10x_303_M","CUP_17Rnd_9x19_glock17"};
        respawnMagazines[] = {"CUP_10x_303_M","CUP_17Rnd_9x19_glock17","CUP_10x_303_M","CUP_17Rnd_9x19_glock17"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_LeeEnfield_rail","","","optic_KHS_old",{"CUP_10x_303_M",10},{},""},{},{"CUP_hgun_Glock17_blk","","","",{"CUP_17Rnd_9x19_glock17",17},{},""},{"U_BG_Guerrilla_6_1",{{"FirstAidKit",2},{"CUP_17Rnd_9x19_glock17",1,17}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_3",{{"SmokeShell",1,1},{"CUP_10x_303_M",10,10},{"CUP_17Rnd_9x19_glock17",2,17}}},{},"","G_Balaclava_oli",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_USMilitia_Militiaman_M72_01 : CUP_O_TK_INS_Soldier_AT_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (M72)";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "CUP_U_I_GUE_Anorak_02";

        linkedItems[] = {"CUP_V_B_ALICE","CUP_H_PMC_Cap_Tan","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_ALICE","CUP_H_PMC_Cap_Tan","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M16A2","rhs_weap_m72a7"};
        respawnWeapons[] = {"CUP_arifle_M16A2","rhs_weap_m72a7"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","rhs_m72a7_mag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","rhs_m72a7_mag","CUP_30Rnd_556x45_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{"rhs_weap_m72a7","","","",{"rhs_m72a7_mag",1},{},""},{},{"CUP_U_I_GUE_Anorak_02",{{"FirstAidKit",2},{"CUP_30Rnd_556x45_Stanag",1,30},{"rhs_m72a7_mag",1,1}}},{"CUP_V_B_ALICE",{{"SmokeShell",2,1},{"CUP_30Rnd_556x45_Stanag",6,30}}},{},"CUP_H_PMC_Cap_Tan","G_Aviator",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_USMilitia_Team_Leader_01 : CUP_O_TK_INS_Soldier_TL_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_TK","LanguagePER_F"};

        uniformClass = "CUP_U_B_GER_BDU_Flecktarn_ODBottom";

        linkedItems[] = {"V_TacVest_camo","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_TacVest_camo","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M4A3_black","CUP_hgun_Glock17_blk","Binocular"};
        respawnWeapons[] = {"CUP_arifle_M4A3_black","CUP_hgun_Glock17_blk","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_17Rnd_9x19_glock17","CUP_30Rnd_556x45_Stanag","CUP_17Rnd_9x19_glock17"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_17Rnd_9x19_glock17","CUP_30Rnd_556x45_Stanag","CUP_17Rnd_9x19_glock17"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M4A3_black","","acc_flashlight","CUP_optic_Eotech553_Black",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{"CUP_hgun_Glock17_blk","","","",{"CUP_17Rnd_9x19_glock17",17},{},""},{"CUP_U_B_GER_BDU_Flecktarn_ODBottom",{{"FirstAidKit",1},{"Chemlight_green",1,1},{"CUP_30Rnd_556x45_Stanag",1,30},{"CUP_17Rnd_9x19_glock17",2,17}}},{"V_TacVest_camo",{{"CUP_30Rnd_556x45_Stanag",2,30},{"CUP_30Rnd_556x45_Emag",4,30},{"SmokeShell",2,1},{"SmokeShellRed",1,1},{"CUP_HandGrenade_M67",2,1},{"CUP_17Rnd_9x19_glock17",1,17}}},{},"","G_Balaclava_blk",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_USMilitia_Sniper_01 : CUP_O_TK_INS_Sniper_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "U_BG_Guerilla2_3";

        linkedItems[] = {"CUP_V_O_Ins_Carrier_Rig","H_Cap_blk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_O_Ins_Carrier_Rig","H_Cap_blk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_FNFAL_railed","Binocular"};
        respawnWeapons[] = {"CUP_arifle_FNFAL_railed","Binocular"};

        magazines[] = {"CUP_20Rnd_762x51_FNFAL_M","CUP_20Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_FNFAL_M","CUP_20Rnd_762x51_FNFAL_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL_railed","","","CUP_optic_SB_11_4x20_PM",{"CUP_20Rnd_762x51_FNFAL_M",20},{},""},{},{},{"U_BG_Guerilla2_3",{{"FirstAidKit",1},{"SmokeShell",1,1},{"SmokeShellBlue",1,1}}},{"CUP_V_O_Ins_Carrier_Rig",{{"CUP_20Rnd_762x51_FNFAL_M",5,20}}},{},"H_Cap_blk","CUP_G_Oakleys_Drk",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_USMilitia_Automatic_Rifleman_01 : CUP_O_TK_INS_Soldier_AR_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Automatic Rifleman";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "CUP_U_I_GUE_Woodland1";

        linkedItems[] = {"CUP_V_B_RRV_MG","H_Cap_blk_CMMG","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_RRV_MG","H_Cap_blk_CMMG","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS","CUP_hgun_Colt1911"};
        respawnWeapons[] = {"CUP_arifle_AKS","CUP_hgun_Colt1911"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_7Rnd_45ACP_1911","CUP_30Rnd_762x39_AK47_M","CUP_7Rnd_45ACP_1911"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_7Rnd_45ACP_1911","CUP_30Rnd_762x39_AK47_M","CUP_7Rnd_45ACP_1911"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS","","","",{"CUP_30Rnd_762x39_AK47_M",30},{},""},{},{"CUP_hgun_Colt1911","","","",{"CUP_7Rnd_45ACP_1911",7},{},""},{"CUP_U_I_GUE_Woodland1",{{"FirstAidKit",1},{"Chemlight_green",1,1},{"CUP_7Rnd_45ACP_1911",2,7}}},{"CUP_V_B_RRV_MG",{{"FirstAidKit",1},{"SmokeShell",1,1},{"CUP_30Rnd_762x39_AK47_M",1,30},{"CUP_75Rnd_TE4_LRT4_Green_Tracer_762x39_RPK_M",2,75},{"CUP_7Rnd_45ACP_1911",1,7}}},{},"H_Cap_blk_CMMG","CUP_G_PMC_Facewrap_Black_Glasses_Dark_Headset",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_USMilitia_Machinegunner_01 : B_USMilitia_Automatic_Rifleman_01 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machinegunner";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "CUP_U_I_GUE_Woodland1";

        linkedItems[] = {"CUP_V_B_RRV_MG","H_Cap_blk_CMMG","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_B_RRV_MG","H_Cap_blk_CMMG","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_lmg_minimi","CUP_hgun_Colt1911"};
        respawnWeapons[] = {"CUP_lmg_minimi","CUP_hgun_Colt1911"};

        magazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_7Rnd_45ACP_1911","CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_7Rnd_45ACP_1911"};
        respawnMagazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_7Rnd_45ACP_1911","CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_7Rnd_45ACP_1911"};

        backpack = "B_AssaultPack_cbr";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_minimi","","","",{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",200},{},""},{},{"CUP_hgun_Colt1911","","","",{"CUP_7Rnd_45ACP_1911",7},{},""},{"CUP_U_I_GUE_Woodland1",{{"FirstAidKit",1},{"Chemlight_green",1,1},{"CUP_7Rnd_45ACP_1911",2,7}}},{"CUP_V_B_RRV_MG",{{"FirstAidKit",1},{"SmokeShell",1,1},{"CUP_7Rnd_45ACP_1911",1,7},{"CUP_200Rnd_TE4_Yellow_Tracer_556x45_M249",1,200}}},{"B_AssaultPack_cbr",{{"CUP_200Rnd_TE4_Yellow_Tracer_556x45_M249",2,200}}},"H_Cap_blk_CMMG","CUP_G_PMC_Facewrap_Black_Glasses_Dark_Headset",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_USMilitia_Humvee_M2_01 : CUP_B_M1151_M2_WDL_USA_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Humvee (M2)";
        side = 2;
        faction = "I_USMilitia";
        crew = "CUP_B_US_Soldier";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\Data\hmmwv_body_canvas_1_wl_co.paa'];_unit setObjectTextureGlobal [1,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\hmmwv_hood_canvas_wl_co.paa'];_unit setObjectTextureGlobal [2,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\hmmwv_regular_wl_1_co.paa'];_unit setObjectTextureGlobal [3,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\hmmwv_parts_wl_1_ca.paa'];_unit setObjectTextureGlobal [4,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\hmmwv_gpk_tower_wl_co.paa'];_unit setObjectTextureGlobal [5,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\hmmwv_gmv_wl_01_co.paa'];_unit setObjectTextureGlobal [6,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\hmmwv_details_2_wl_co.paa'];_unit setObjectTextureGlobal [7,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\stryker_net_co.paa'];_unit setObjectTextureGlobal [8,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\hmmwv_m1167turret_wl_co.paa'];_unit setObjectTextureGlobal [9,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\stryker_net_Des_co.paa'];_unit setObjectTextureGlobal [10,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\hmmwv_m1167turret_wl_co.paa'];_unit setObjectTextureGlobal [11,'\CUP\WheeledVehicles\CUP_WheeledVehicles_UpHMMWV\data\fbcb2_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Woodland";

    };

    class I_USMilitia_Asst_Machinegunner_01 : B_USMilitia_Militiaman_Modified_AR_01 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Asst. Machinegunner";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguagePER_F"};

        uniformClass = "CUP_U_B_US_BDU";

        linkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_US_patrol_cap_OD","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_RACS_Carrier_Rig_wdl_2","CUP_H_US_patrol_cap_OD","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_M4A1"};
        respawnWeapons[] = {"CUP_arifle_M4A1"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};

        backpack = "B_AssaultPack_blk";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M4A1","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_B_US_BDU",{{"FirstAidKit",2},{"CUP_30Rnd_556x45_Stanag",1,30}}},{"CUP_V_I_RACS_Carrier_Rig_wdl_2",{{"SmokeShell",2,1},{"CUP_30Rnd_556x45_Stanag",2,30}}},{"B_AssaultPack_blk",{{"CUP_30Rnd_556x45_PMAG_QP_Tan",2,30}}},"CUP_H_US_patrol_cap_OD","CUP_G_Oakleys_Drk",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_USMilitia_Partisan_01 : C_man_1_OCimport_02 {
        author = "charlie";
        scope = 2;
        scopeCurator = 2;
        displayName = "Partisan";
        side = 2;
        faction = "I_USMilitia";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","G_CIVIL_male"};

        uniformClass = "U_I_C_Soldier_Bandit_2_F";

        linkedItems[] = {"CUP_V_I_Carrier_Belt","H_Bandanna_cbr","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_I_Carrier_Belt","H_Bandanna_cbr","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_AKS"};
        respawnWeapons[] = {"CUP_arifle_AKS"};

        magazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x39_AK47_M","CUP_30Rnd_762x39_AK47_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_AKS","","","",{"CUP_30Rnd_762x39_AK47_M",30},{},""},{},{},{"U_I_C_Soldier_Bandit_2_F",{}},{"CUP_V_I_Carrier_Belt",{{"CUP_30Rnd_762x39_AK47_M",3,30}}},{},"H_Bandanna_cbr","G_Aviator",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};