//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 192.145639 on Stable branch
// Generated with ALiVE version 1.11.3.1905291
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class Indep {

        class I_USMilitia {
            name = "US Local Militia";

            class Infantry {
                name = "Infantry";

                class i_usmilitia_infantry_militia_group {
                    name = "Militia Group";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.7;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M16A2_01";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                    class Unit4 {
                        position[] = {9,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Modified_AR_01";
                    };
                    class Unit5 {
                        position[] = {11,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit6 {
                        position[] = {13,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Automatic_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {15,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Sniper_01";
                    };
                    class Unit8 {
                        position[] = {17,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Hunting_Rifle_01";
                    };
                    class Unit9 {
                        position[] = {19,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "I_USMilitia_Militiaman_FN_FAL_01";
                    };
                };

                class i_usmilitia_infantry_militia_patrol {
                    name = "Militia Patrol";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M16A2_01";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Automatic_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Modified_AR_01";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Hunting_Rifle_01";
                    };
                    class Unit4 {
                        position[] = {9,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "I_USMilitia_Militiaman_FN_FAL_01";
                    };
                };

                class i_usmilitia_infantry_militia_team_aa {
                    name = "Militia Team (AA)";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_AA_Specialist_01";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_AA_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_AA_Specialist_01";
                    };
                };

                class i_usmilitia_infantry_militia_team_at {
                    name = "Militia Team (AT)";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Modified_AR_01";
                    };
                };

                class i_usmilitia_infantry_militia_demolitions_team {
                    name = "Militia Demolitions Team";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Mechanic_01";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Mechanic_01";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militia_Bomb_Builder_01";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militia_Bomb_Builder_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class i_usmilitia_motorized_technicals {
                    name = "Technicals";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {3,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {-5,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CUP_O_LR_SPG9_TKM";
                    };
                    class Unit2 {
                        position[] = {-5,-7,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CUP_O_LR_MG_TKM";
                    };
                    class Unit3 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                };

                class i_usmilitia_motorized_motorized_group {
                    name = "Motorized Group";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.1;

                    class Unit0 {
                        position[] = {3,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {-5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CUP_O_Ural_ZU23_TKM";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M16A2_01";
                    };
                    class Unit4 {
                        position[] = {9,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                    class Unit5 {
                        position[] = {11,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Militiaman_FN_FAL_01";
                    };
                    class Unit6 {
                        position[] = {13,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit7 {
                        position[] = {15,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit8 {
                        position[] = {17,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Automatic_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {19,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Sniper_01";
                    };
                    class Unit10 {
                        position[] = {21,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Modified_AR_01";
                    };
                };

                class i_usmilitia_motorized_motorized_patrol_humvee {
                    name = "Motorized Patrol (Humvee)";
                    side = 2;
                    faction = "I_USMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {3,5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "B_USMilitia_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit2 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Machinegunner_01";
                    };
                    class Unit3 {
                        position[] = {9,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_M72_01";
                    };
                    class Unit4 {
                        position[] = {11,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "I_USMilitia_Militiaman_FN_FAL_01";
                    };
                    class Unit5 {
                        position[] = {13,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "B_USMilitia_Militiaman_Hunting_Rifle_01";
                    };
                    class Unit6 {
                        position[] = {-13,0,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_USMilitia_Humvee_M2_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};